@startuml
'https://plantuml.com/class-diagram

class Solution43 {
+main()
WebsiteGenerator d
}

class WebsiteGenerator {
String path
+createWebsite(String websiteName)
}

Solution43 --o WebsiteGenerator

@enduml